import streamlit as st
import pandas as pd
import os
from dotenv import load_dotenv
from sheets import get_sheet, log_call, get_client_history
from agent1C import generate_call_list
load_dotenv()
SHEET_NAME = os.getenv("GOOGLE_SHEET_NAME") or st.secrets.get("GOOGLE_SHEET_NAME")
@st.cache_data(ttl=10800)  # cache for 3 hour
def get_call_list():
    return generate_call_list(SHEET_NAME)


call_list, skipped = get_call_list()
st.set_page_config(page_title="Collection Agent", layout="wide")


page = st.sidebar.selectbox("Navigate", [
    "Today's Call List",
    "Log a Call",
    "Client History"
])


###Screen1 - Today's Call List


if page == "Today's Call List":
    st.title("Today's Call List")
    
    st.caption("Auto-generated by Agent1C based on days pending")
    
    with st.spinner("Agent is thinking..."):
        call_list, skipped = get_call_list()

    st.markdown(f"### {len(call_list)} clients to call today")
    st.divider()

    for row in call_list:
        priority = row.get("priority", "")
        label = f"{priority} &nbsp; {row['Client Name']}** - {row['Balance']} - {row['Days_Pending']} days pending"

        with st.expander(label):
            col1, col2 = st.columns(2)
            with col1:
                st.write(f"**LR No:** {row.get('LR-No', '-')}")
                st.write(f"**Route:** {row.get('Source','-')} -> {row.get('Destination', '-')}")
                st.write(f"**Vehicle:** {row.get('Vehicle No.', '-')}")
            with col2:
                st.write(f"**Invoice:** {row.get('Invoice Generated', '-')}")
                st.write(f"**Recieved:** {row.get('Payment Recieved', '-')}")
                st.write(f"**Balance:** {row.get('Balance', '-')}")
            st.write(f"**Basis:** {row.get('decision_basis', '-')}")
            st.write(f"**Remarks:** {row.get('Remarks', '-')}")

    with st.expander(f"--> Skipped today - {len(skipped)} clients"):
        for row in skipped:
            st.write(f"- **{row.get('Client Name', '-')}** - {row.get('skip-reason', '-')}")
    if st.button("🔄 Refresh Call List"):
        st.cache_data.clear()
        st.rerun()
####Screen3 - Logging a call.####

elif page == "Log a Call":
    st.title("Log a Call")
    st.caption("Fill this after every call")

    with st.spinner("Loading today's call list..."):
        call_list, _ = get_call_list()
    if not call_list:
        st.success("No calls needed today!")
    else:
        client_options = [
            f"{row['Client Name']} - {row['Balance']}"
            for row in call_list
        ]
        selected = st.selectbox("Select Client you called", client_options)

        selected_index = client_options.index(selected)
        client_data = call_list[selected_index]

        ##ShowContext
        st.info(
            f"**Balance:** {client_data['Balance']} &nbsp;|&nbsp; "
            f"**Days Pending:** {client_data['Days_Pending']} &nbsp;|&nbsp; "
            f"**Route:** {client_data.get('Source','-')} --> {client_data.get('Destination','-')} "
        )

        lr_no = st.text_input("LR Number", value=str(client_data.get("LR-No", "")))
        call_status = st.selectbox("Call Status", [
            "Answered",
            "Non Reachable",
            "Busy",
            "Call Back Requested"
        ])
        what_client_said = st.text_area("what did client say?", height=100)
        promise_date = st.date_input("Promise Date(if any)")
        notes = st.text_input("Additional Notes (optional)")

        if st.button("Save Call Log",type='primary'):
            if what_client_said:
                success = log_call(
                    client_name=client_data['Client Name'],
                    lr_no=lr_no,
                    call_status=call_status,
                    what_client_said=what_client_said,
                    promise_date=str(promise_date),
                    notes=notes
                )
                if success:
                    st.success("Call logged successfully!")
                    st.balloons()
            else:
                st.warning("Please enter what client said.")
####Screen3 - CLient History####
elif page == "Client History":
    st.title("Client History")

    data  = get_sheet(SHEET_NAME)
    all_logs = get_sheet("Agent_Call_Logs")

    client_names = sorted(set([
        row["Client Name"] for row in data
        if row.get("Client Name")
    ]))

    selected = st.selectbox("Select Client" , client_names)

    client_rows = [r for r in data if r["Client Name"] == selected]
    if client_rows:
        st.markdown("###Ledger Entries")
        df = pd.DataFrame(client_rows)
        st.dataframe(df, use_container_width=True)

    history = [
        row for row in all_logs
        if row['Client Name'].strip().lower() == selected.strip().lower()
    ]
    st.markdown(f"### Call History - {len(history)} calls logged")
    if not history:
        st.warning("No calls logged yet for this client.")
    else:
        df_logs = pd.DataFrame(history)
        st.dataframe(df_logs, use_container_width=True)
